### ISSUE TITLE
error when starting server and also when loding boss menu 

### ISSUE THREAD

**Issue by Livewithrusty** [ESX-Org/esx_society#71]
keep geting this error on server start

Error resuming coroutine: server/main.lua:26: attempt to index a nil value (field ‘?’)
stack traceback:
server/main.lua:26: in local ‘cb’
@mysql-async/lib/MySQL.lua:204: in upvalue ‘handler’
citizen:/scripting/lua/scheduler.lua:219: in function citizen:/scripting/lua/scheduler.lua:218
Error running call reference function for resource esx_society: citizen:/scripting/lua/scheduler.lua:403: server/main.lua:182: attempt to index a nil value (field ‘?’)
stack traceback:
server/main.lua:182: in upvalue ‘ref’
citizen:/scripting/lua/scheduler.lua:389: in function citizen:/scripting/lua/scheduler.lua:388
[C]: in function ‘xpcall’
citizen:/scripting/lua/scheduler.lua:388: in function citizen:/scripting/lua/scheduler.lua:387
stack traceback:
[C]: in function ‘error’
citizen:/scripting/lua/scheduler.lua:403: in function citizen:/scripting/lua/scheduler.lua:372
e[91mError: Unhandled error: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
at h (citizen:/scripting/v8/msgpack.js:29:15761)
at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
at unpack (citizen:/scripting/v8/main.js:20:33)
at citizen:/scripting/v8/main.js:51:11
at setImmediate (mysql-async.js:4962:9)
at Object.callback (citizen:/scripting/v8/timer.js:56:6)e[0m

**Comment by DayZen16** [comment]
I have the same exact issue. Did you get it resolved?
